
/**
 * This file is AUTO GENERATED by [msw-auto-mock](https://github.com/zoubingwu/msw-auto-mock)
 * Feel free to commit/edit it as you need.
 */
/* eslint-disable */
/* tslint:disable */
import { setupWorker, rest } from "msw";
import { faker } from "@faker-js/faker";
import { pokemonTypes } from "./components/pokemonTypes";

faker.seed(13);

const baseURL = "https://localhost:7092";

const MAX_ARRAY_LENGTH = 20;

let i = 0;
const next = () => {
  if (i === Number.MAX_SAFE_INTEGER - 1) {
    i = 0;
  }
  return i++;
};

export const handlers = [
  rest.get(`${baseURL}/Pokemon`, (_, res, ctx) => {
    const resultArray = [
      [
        ctx.status(200),
        ctx.json(
          [
            ...new Array(
              faker.datatype.number({ max: MAX_ARRAY_LENGTH })
            ).keys(),
          ].map((_) => ({
            id: faker.datatype.number(255),
            name: {
              english: faker.lorem.slug(1),
              japanese: faker.lorem.slug(1),
              chinese: faker.lorem.slug(1),
              french: faker.lorem.slug(1),
            },
            type: [
              ...new Array(
                faker.datatype.number({ max: MAX_ARRAY_LENGTH })
              ).keys(),
            ].map((_) =>pokemonTypes[faker.datatype.number()%10].name),
            base: {
              hp: faker.datatype.number(),
              attack: faker.datatype.number(),
              defense: faker.datatype.number(),
              spAttack: faker.datatype.number(),
              spDefense: faker.datatype.number(),
              speed: faker.datatype.number(),
            },
          }))
        ),
      ],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.get(`${baseURL}/api/Values`, (_, res, ctx) => {
    const resultArray = [
      [
        ctx.status(200),
        ctx.json(
          [
            ...new Array(
              faker.datatype.number({ max: MAX_ARRAY_LENGTH })
            ).keys(),
          ].map((_) => faker.lorem.slug(1))
        ),
      ],
    ];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.post(`${baseURL}/api/Values`, (_, res, ctx) => {
    const resultArray = [[ctx.status(200), ctx.json(null)]];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.get(`${baseURL}/api/Values/:id`, (_, res, ctx) => {
    const resultArray = [[ctx.status(200), ctx.json(faker.lorem.slug(1))]];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.put(`${baseURL}/api/Values/:id`, (_, res, ctx) => {
    const resultArray = [[ctx.status(200), ctx.json(null)]];

    return res(...resultArray[next() % resultArray.length]);
  }),
  rest.delete(`${baseURL}/api/Values/:id`, (_, res, ctx) => {
    const resultArray = [[ctx.status(200), ctx.json(null)]];

    return res(...resultArray[next() % resultArray.length]);
  }),
];

// This configures a Service Worker with the given request handlers.
export const startWorker = () => {
  const worker = setupWorker(...handlers);
  worker.start();
};
